In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [3]:
iris= load_iris()
dt_clf = DecisionTreeClassifier()

In [4]:
iris_data = iris.data

In [5]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
iris_label = iris.target

In [7]:
iris_df = pd.DataFrame(data=iris_data, columns= iris.feature_names)
iris_df["label"] = iris.target
iris_df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),label
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0


In [8]:
from sklearn.model_selection import train_test_split, KFold

In [11]:
X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label,
                                                    test_size=0.2, random_state=1)

In [12]:
dt_clf = DecisionTreeClassifier(random_state=13)
dt_clf.fit(X_train,y_train)

DecisionTreeClassifier(random_state=13)

In [13]:
pred = dt_clf.predict(X_test)

In [14]:
pred

array([0, 1, 1, 0, 2, 1, 2, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       2, 0, 2, 1, 0, 0, 1, 2])

In [15]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,pred)

0.9666666666666667

In [16]:

features = iris.data
label = iris.target
kfold = KFold(n_splits=5)
cv_accuracy=[]

In [17]:
n_iter=0

for train_index, test_index in kfold.split(features):
    X_train, X_test = features[train_index], features[test_index]
    y_train , y_test = label[train_index], label[test_index]
    
    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_test)
    n_iter +=1
    
    accuracy = np.round(accuracy_score(y_test,pred),4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    cv_accuracy.append(accuracy)
    
 

In [18]:
print(cv_accuracy)
print(np.mean(cv_accuracy))

[1.0, 1.0, 0.8667, 0.9333, 0.7333]
0.9066599999999999


In [19]:
features = iris.data
label = iris.target
kfold2 = KFold(n_splits=3)
cv_accuracy2=[]

In [20]:
n_iter=0

for train_index, test_index in kfold2.split(features):
    X_train, X_test = features[train_index], features[test_index]
    y_train , y_test = label[train_index], label[test_index]
    
    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_test)
    n_iter +=1
    
    accuracy = np.round(accuracy_score(y_test,pred),4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    cv_accuracy2.append(accuracy)
    

In [21]:
print(cv_accuracy2)
print(np.mean(cv_accuracy2))

[0.0, 0.0, 0.0]
0.0


In [22]:
iris = load_iris()

iris_df = pd.DataFrame(data=iris.data,columns=iris.feature_names)
iris_df["label"] = iris.target
iris_df["label"].value_counts()

0    50
1    50
2    50
Name: label, dtype: int64

In [24]:
kfold= KFold(n_splits=3)
n_iter = 0
for train_index, test_index in kfold.split(iris_df):
    n_iter +=1
    label_train = iris_df["label"].iloc[train_index]
    label_test = iris_df['label'].iloc[test_index]
    print(label_train.value_counts())
    print(label_test.value_counts())

1    50
2    50
Name: label, dtype: int64
0    50
Name: label, dtype: int64
0    50
2    50
Name: label, dtype: int64
1    50
Name: label, dtype: int64
0    50
1    50
Name: label, dtype: int64
2    50
Name: label, dtype: int64


In [25]:
from sklearn.model_selection import StratifiedKFold
skf = StratifiedKFold(n_splits=3)
n_iter = 0
for train_index, test_index in skf.split(iris_df,iris_df['label']):
    n_iter +=1
    label_train = iris_df["label"].iloc[train_index]
    label_test = iris_df['label'].iloc[test_index]
    print(label_train.value_counts())
    print(label_test.value_counts())

2    34
0    33
1    33
Name: label, dtype: int64
0    17
1    17
2    16
Name: label, dtype: int64
1    34
0    33
2    33
Name: label, dtype: int64
0    17
2    17
1    16
Name: label, dtype: int64
0    34
1    33
2    33
Name: label, dtype: int64
1    17
2    17
0    16
Name: label, dtype: int64


In [26]:
skfold = StratifiedKFold(n_splits=3)
n_iter = 0
cv_accuracy3=[]
for train_index, test_index in skfold.split(features,label):
    X_train, X_test = features[train_index], features[test_index]
    y_train , y_test = label[train_index], label[test_index]
    
    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_test)
    
    n_iter +=1
    accuracy = np.round(accuracy_score(y_test,pred),4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    cv_accuracy3.append(accuracy)

print(np.round(cv_accuracy3,4))
print(np.mean(cv_accuracy3))

[0.98 0.94 0.98]
0.9666666666666667


In [27]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, cross_validate

In [30]:
iris_data= load_iris()
dt_clf = DecisionTreeClassifier(random_state=152)

data = iris_data.data
label = iris_data.target

scores = cross_val_score(dt_clf,data,label,scoring='accuracy',cv=3)
print(np.round(scores,4))
print(np.round(np.mean(scores),4))

[0.98 0.94 0.98]
0.9667
